CG-RJK8hmewzGZMgR1PHncrkr84

In [16]:
from pycoingecko import CoinGeckoAPI
import pandas as pd
import requests

##### Coingecko API to get the top 20 cryptos

In [17]:
def fetch_top_coins_tickers(vs_currency='usd', limit=30):
    url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids&x_cg_demo_api_key=CG-RJK8hmewzGZMgR1PHncrkr84'
    params = {
        'vs_currency': vs_currency,
        'order': 'market_cap_desc',
        'per_page': limit,
        'page': 1,
        'sparkline': False,
        'price_change_percentage': '24h'
    }
    response = requests.get(url, params=params)
    if response.status_code != 200:
        print(f"Error fetching data: Status code {response.status_code}")
        return []

    data = response.json()

##Extract tickers
    tickers = [coin['name'].upper() for coin in data]
    return tickers

In [18]:
top_coins = fetch_top_coins_tickers(vs_currency='usd', limit=25)
print(top_coins)

['BITCOIN', 'ETHEREUM', 'TETHER', 'XRP', 'BNB', 'SOLANA', 'USDC', 'CARDANO', 'DOGECOIN', 'TRON', 'LIDO STAKED ETHER', 'WRAPPED BITCOIN', 'CHAINLINK', 'TONCOIN', 'LEO TOKEN', 'WRAPPED STETH', 'STELLAR', 'AVALANCHE', 'USDS', 'HEDERA', 'SHIBA INU', 'SUI', 'LITECOIN', 'POLKADOT', 'PI NETWORK']

In [ ]:
# Specify the symbols for the cryptocurrencies you are interested in
symbols = [f"{coin}-USD" for coin in top_coins]  


df = pd.DataFrame()

# Specify the date range
start_date = '2011-9-1'
end_date = int(datetime.now().timestamp())

# Fetch the historical data for each symbol
for symbol in symbols:
    print(f"Fetching data for {symbol}...")
    data = yf.download(symbol, start=start_date, end=end_date)
    if not data.empty:
        data['Symbol'] = symbol.replace('-USD', '')  
        df = pd.concat([df, data], axis=0)


df.reset_index(inplace=True)

In [19]:
import yfinance as yf
import datetime

import requests
import datetime
import time
import pandas as pd
import ta








# Configuration
api_key = "CG-RJK8hmewzGZMgR1PHncrkr84"  # Replace with your actual CoinGecko Pro API key
coin_id = 'bitcoin'
vs_currency = 'usd'

# Calculate timestamps for one year range
end_date = datetime.datetime.now()
start_date = end_date - datetime.timedelta(days=365)
start_timestamp = int(time.mktime(start_date.timetuple()))
end_timestamp = int(time.mktime(end_date.timetuple()))

# API endpoint and parameters for CoinGecko API
url = f'https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart/range'
params = {
    'vs_currency': vs_currency,
    'from': start_timestamp,
    'to': end_timestamp,
    'x_cg_demo_api_key': 'CG-RJK8hmewzGZMgR1PHncrkr84'
}
headers = {
    'accept': 'application/json'
}

# Fetch data using requests with headers
response = requests.get(url, headers=headers, params=params)
if response.status_code != 200:
    raise Exception(f"Failed to fetch data: {response.status_code} - {response.text}")

data = response.json()

# Extract and process data as before
prices = data.get("prices", [])
market_caps = data.get("market_caps", [])
volumes = data.get("total_volumes", [])

df_prices = pd.DataFrame(prices, columns=["timestamp", "closing_price"])
df_market_caps = pd.DataFrame(market_caps, columns=["timestamp", "market_cap"])
df_volumes = pd.DataFrame(volumes, columns=["timestamp", "volume"])

df = df_prices.merge(df_market_caps, on="timestamp").merge(df_volumes, on="timestamp")
#df['date'] = pd.to_datetime(df['timestamp'], unit='ms').dt.date
#df['coin_name'] = coin_id.capitalize()
#df = df[['date', 'coin_name', 'closing_price', 'volume', 'market_cap']]
#df['closing_price'] = df['closing_price'].astype(float)
#df['rsi_14'] = ta.momentum.rsi(df['closing_price'], window=14)

Fetching data for BITCOIN-USD...

[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['BITCOIN-USD']: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

Fetching data for ETHEREUM-USD...

[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['ETHEREUM-USD']: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

Fetching data for TETHER-USD...

[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['TETHER-USD']: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

Fetching data for XRP-USD...

[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['XRP-USD']: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

Fetching data for BNB-USD...

[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['BNB-USD']: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

Fetching data for SOLANA-USD...

[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['SOLANA-USD']: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

Fetching data for USDC-USD...

[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['USDC-USD']: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

Fetching data for CARDANO-USD...

Failed to get ticker 'CARDANO-USD' reason: Expecting value: line 1 column 1 (char 0)

KeyboardInterrupt:

In [5]:
url = 'https://api.coingecko.com/api/v3/simple/price'
params = {  
         'ids': 'ethereum',
         'vs_currencies': 'USD'
}

 # Replace 'YOUR_API_KEY' with your actual API key
headers = { 'x-cg-demo-api-key': 'CG-RJK8hmewzGZMgR1PHncrkr84' }

response = requests.get(url, params = params)

In [6]:
if response.status_code == 200:
         data = response.json()
         Ethereum_price = data['ethereum']['usd']
         print(f'The price of Ethereum in USD is ${Ethereum_price}')
else:
         print('Failed to retrieve data from the API')

The price of Ethereum in USD is $1985.27

In [7]:
cg = CoinGeckoAPI()
ohlc = cg.get_coin_ohlc_by_id(id = 'ethereum', vs_currency = 'usd', days = '30')


df = pd.DataFrame(ohlc)

In [8]:
df

                 0        1        2        3        4
0    1740110400000  2739.73  2748.23  2729.27  2741.39
1    1740124800000  2744.83  2766.62  2744.83  2756.20
2    1740139200000  2756.13  2812.44  2752.20  2793.79
3    1740153600000  2791.83  2838.89  2715.46  2730.66
4    1740168000000  2714.75  2763.31  2625.09  2637.06
..             ...      ...      ...      ...      ...
175  1742630400000  1985.30  1990.41  1983.37  1984.90
176  1742644800000  1984.39  2002.85  1982.23  1988.15
177  1742659200000  1989.03  1994.55  1982.89  1986.31
178  1742673600000  1986.63  1997.93  1984.50  1993.74
179  1742688000000  1995.14  2000.26  1974.92  1979.54

[180 rows x 5 columns]

In [9]:
df.columns = ['date', 'open', 'high', 'low', 'close']
df['date'] = pd.to_datetime(df['date'], unit = 'ms')
df.set_index('date', inplace = True)

In [10]:
df

                        open     high      low    close
date
2025-02-21 04:00:00  2739.73  2748.23  2729.27  2741.39
2025-02-21 08:00:00  2744.83  2766.62  2744.83  2756.20
2025-02-21 12:00:00  2756.13  2812.44  2752.20  2793.79
2025-02-21 16:00:00  2791.83  2838.89  2715.46  2730.66
2025-02-21 20:00:00  2714.75  2763.31  2625.09  2637.06
...                      ...      ...      ...      ...
2025-03-22 08:00:00  1985.30  1990.41  1983.37  1984.90
2025-03-22 12:00:00  1984.39  2002.85  1982.23  1988.15
2025-03-22 16:00:00  1989.03  1994.55  1982.89  1986.31
2025-03-22 20:00:00  1986.63  1997.93  1984.50  1993.74
2025-03-23 00:00:00  1995.14  2000.26  1974.92  1979.54

[180 rows x 4 columns]

### Historical Data

In [7]:
from pycoingecko import CoinGeckoAPI
cg = CoinGeckoAPI()
ohlc = cg.get_coin_ohlc_by_id(id = 'ethereum', vs_currency = 'usd', days = '30')

import pandas as pd
df = pd.DataFrame(ohlc)
df.columns = ['date', 'open', 'high', 'low', 'close']
df['date'] = pd.to_datetime(df['date'], unit = 'ms')
df.set_index('date', inplace = True)

In [8]:
from pycoingecko import CoinGeckoAPI
import pandas as pd

cg = CoinGeckoAPI()
ohlc = cg.get_coin_ohlc_by_id(id='ethereum', vs_currency='usd', days='365')
df = pd.DataFrame(ohlc)
df.columns = ['date', 'open', 'high', 'low', 'close']
df['date'] = pd.to_datetime(df['date'], unit='ms')
df.set_index('date', inplace=True)

In [9]:
import requests

def get_fear_greed_index():
    url = "https://api.alternative.me/fng/"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        # Extract the current value and sentiment classification
        result = data['data'][0]  # Most recent data point
        value = result['value']
        classification = result['value_classification']
        return value, classification
    else:
        return None, None

fear_greed_value, sentiment = get_fear_greed_index()
print(f"Fear & Greed Index: {fear_greed_value}, Sentiment: {sentiment}")

Fear & Greed Index: 61, Sentiment: Greed

##### All supported Coins

In [10]:
import requests
import pandas as pd

url = "https://api.coingecko.com/api/v3/coins/list"
headers = {"accept": "application/json"}

response = requests.get(url, headers=headers)

# Parse the JSON response
data = response.json()

# Convert to Pandas DataFrame
df = pd.DataFrame(data)

# Display the first few rows of the DataFrame
df

                             id symbol                      name
0                        01coin    zoc                    01coin
1                        0chain    zcn                       Zus
2                          0dog   0dog              Bitcoin Dogs
3           0-knowledge-network    0kn       0 Knowledge Network
4                         0-mee    ome                     O-MEE
...                         ...    ...                       ...
16648                 zyncoin-2    zyn                   ZynCoin
16649                  zynecoin    zyn                  Zynecoin
16650                     zyrri    zyr                     Zyrri
16651                       zzz    zzz               GoSleep ZZZ
16652  z-z-z-z-z-fehu-z-z-z-z-z      ᚠ  Z•Z•Z•Z•Z•FEHU•Z•Z•Z•Z•Z

[16653 rows x 3 columns]

#### Trending Crypto Price Data

In [11]:
url = 'https://api.coingecko.com/api/v3/search/trending'
headers = {
         'accept': 'application/json'
}
response = requests.get(url, headers = headers)

In [12]:
if response.status_code == 200:
         # Convert the JSON response to a Python dictionary
         data = response.json()

         # Extract relevant fields from the JSON data (coins section)
         coin_data = []
         for coin in data.get('coins', []):
            coin_item = coin.get('item', {})
            coin_data.append({
            'id': coin_item.get('id', ''),
            'name': coin_item.get('name', ''),
            'symbol': coin_item.get('symbol', ''),
            'market_cap_rank': coin_item.get('market_cap_rank', 0),
            'score': coin_item.get('score', 0)
     })

         # Create a DataFrame from the extracted data
         df = pd.DataFrame(coin_data)

         # Display the DataFrame
         df

else:

         print(f"API request failed with status code: {response.status_code}")

In [13]:
df

                   id               name    symbol  market_cap_rank  score
0               ai16z              ai16z     AI16Z               95      0
1    virtual-protocol  Virtuals Protocol   VIRTUAL               54      1
2            fartcoin           Fartcoin  FARTCOIN              109      2
3                meow               MEOW      MEOW              291      3
4            griffain           GRIFFAIN  GRIFFAIN              234      4
5             heyanon           Hey Anon      ANON              358      5
6                 sui                Sui       SUI               13      6
7             sonic-3  Sonic (prev. FTM)         S               61      7
8              ripple                XRP       XRP                3      8
9               aixbt  aixbt by Virtuals     AIXBT              233      9
10           ethereum           Ethereum       ETH                2     10
11             solana             Solana       SOL                6     11
12             cookie         Cookie DAO    COOKIE              436     12
13        hyperliquid        Hyperliquid      HYPE               28     13
14  aerodrome-finance  Aerodrome Finance      AERO              131     14

### Features

**Historical Price Chart** Plot the price over time (line chart or candlestick chart) to show the coin's historical performance.
Add options to view data for different timeframes (e.g., 1 day, 7 days, 1 month, 1 year).

**Market Cap vs. Volume** - Plot the market capitalization and trading volume over time.

**Relative Strength Index (RSI)**-  Plot the RSI to measure the coin's momentum and potential overbought/oversold conditions.

 **Bitcoin Dominance** This is the percentage of Bitcoin's market cap relative to the total crypto market cap, which can indicate shifts in investor sentiment. DO thi over teh years

In [14]:
'CG-RJK8hmewzGZMgR1PHncrkr84'

'CG-RJK8hmewzGZMgR1PHncrkr84'

#### crypto data

In [15]:
parameters = {
         'vs_currency': 'usd',
         'order': 'market_cap_desc',
         'per_page': 100,
         'page': 1,
         'sparkline': False,
         'locale': 'en'
         }
coin_market_data = cg.get_coins_markets(**parameters)

df = pd.DataFrame(coin_market_data)
df = df.drop(['id', 'symbol', 'image', 'high_24h', 'low_24h', 'price_change_24h', 
'market_cap_change_24h','market_cap_change_percentage_24h', 'fully_diluted_valuation', 'ath_date', 'ath_change_percentage',
'atl_change_percentage', 'atl_date', 'roi'],  axis = 1)
df

,name,current_price,market_cap,market_cap_rank,total_volume,price_change_percentage_24h,circulating_supply,total_supply,max_supply,ath,atl,last_updated
0,Bitcoin,94347.000000,1868813260711,1,75800350932,-0.09000,1.980951e+07,2.100000e+07,2.100000e+07,108135.000000,67.810000,2025-01-13T23:39:46.433Z
1,Ethereum,3132.390000,377420651895,2,41682048498,-3.87226,1.204930e+08,1.204930e+08,NaN,4878.260000,0.432979,2025-01-13T23:39:48.073Z
2,XRP,2.520000,144799619829,3,9340777833,0.66514,5.749312e+10,9.998667e+10,1.000000e+11,3.400000,0.002686,2025-01-13T23:39:51.885Z
3,Tether,0.999588,137394172110,4,62778694631,0.01259,1.374497e+11,1.374497e+11,NaN,1.320000,0.572521,2025-01-13T23:39:48.005Z
4,BNB,687.290000,100241199153,5,1306163558,-0.81258,1.458876e+08,1.458876e+08,2.000000e+08,788.840000,0.039818,2025-01-13T23:39:52.851Z
...,...,...,...,...,...,...,...,...,...,...,...,...
95,sUSDS,1.031000,1240662611,97,543515,-0.18034,1.204051e+09,1.204051e+09,NaN,1.061000,0.961716,2025-01-13T23:39:44.771Z
96,NEXO,1.240000,1239472027,96,10847708,-0.52675,1.000000e+09,1.000000e+09,1.000000e+09,4.070000,0.045153,2025-01-13T23:39:54.164Z
97,Solv Protocol SolvBTC,93466.000000,1212982673,98,12657793,-0.85376,1.297759e+04,1.298301e+04,2.100000e+07,107779.000000,49058.000000,2025-01-13T23:39:44.266Z
98,Kaia,0.205004,1201796915,99,45372011,-1.25047,5.856642e+09,5.856642e+09,NaN,0.406698,0.113064,2025-01-13T23:39:52.915Z
99,Maker,1345.350000,1198595790,100,108082971,-5.18863,8.910943e+05,9.196937e+05,1.005577e+06,6292.310000,168.360000,2025-01-13T23:39:53.620Z

for that add that and make it show the coin, price nad the top movnig the paast 24 hours, market cap

#### Historical data

In [16]:
import requests
import datetime
import time
import pandas as pd
import ta

# Configuration
api_key = "CG-RJK8hmewzGZMgR1PHncrkr84"  # Replace with your actual CoinGecko Pro API key
coin_id = 'bitcoin'
vs_currency = 'usd'

# Calculate timestamps for one year range
end_date = datetime.datetime.now()
start_date = end_date - datetime.timedelta(days=365)
start_timestamp = int(time.mktime(start_date.timetuple()))
end_timestamp = int(time.mktime(end_date.timetuple()))

# API endpoint and parameters for CoinGecko API
url = f'https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart/range'
params = {
    'vs_currency': vs_currency,
    'from': start_timestamp,
    'to': end_timestamp,
    'x_cg_demo_api_key': 'CG-RJK8hmewzGZMgR1PHncrkr84'
}
headers = {
    'accept': 'application/json'
}

# Fetch data using requests with headers
response = requests.get(url, headers=headers, params=params)
if response.status_code != 200:
    raise Exception(f"Failed to fetch data: {response.status_code} - {response.text}")

data = response.json()

# Extract and process data as before
prices = data.get("prices", [])
market_caps = data.get("market_caps", [])
volumes = data.get("total_volumes", [])

df_prices = pd.DataFrame(prices, columns=["timestamp", "closing_price"])
df_market_caps = pd.DataFrame(market_caps, columns=["timestamp", "market_cap"])
df_volumes = pd.DataFrame(volumes, columns=["timestamp", "volume"])

df = df_prices.merge(df_market_caps, on="timestamp").merge(df_volumes, on="timestamp")
df['date'] = pd.to_datetime(df['timestamp'], unit='ms').dt.date
df['coin_name'] = coin_id.capitalize()
df = df[['date', 'coin_name', 'closing_price', 'volume', 'market_cap']]
df['closing_price'] = df['closing_price'].astype(float)
df['rsi_14'] = ta.momentum.rsi(df['closing_price'], window=14)

In [18]:
df.to_csv('data/btc_historical_data.csv', index=False)

:

In [17]:
df

,date,coin_name,closing_price,volume,market_cap,rsi_14
0,2024-01-15,Bitcoin,41800.932822,1.696896e+10,8.229071e+11,NaN
1,2024-01-16,Bitcoin,42587.336038,2.263453e+10,8.352260e+11,NaN
2,2024-01-17,Bitcoin,43148.001643,2.202312e+10,8.457709e+11,NaN
3,2024-01-18,Bitcoin,42713.859187,2.129906e+10,8.369880e+11,NaN
4,2024-01-19,Bitcoin,41261.394798,2.516043e+10,8.088458e+11,NaN
...,...,...,...,...,...,...
360,2025-01-09,Bitcoin,95016.714410,6.579047e+10,1.885313e+12,46.157392
361,2025-01-10,Bitcoin,92376.275783,6.585088e+10,1.832934e+12,41.638593
362,2025-01-11,Bitcoin,94736.626742,6.343366e+10,1.876837e+12,46.665228
363,2025-01-12,Bitcoin,94559.551672,1.783642e+10,1.874286e+12,46.342751
364,2025-01-13,Bitcoin,94454.770896,1.960893e+10,1.870315e+12,46.139568

 **Fear and Greed Index**: If available, this index captures the general market sentiment, which can influence asset prices and is particularly useful for crypto markets.

Social Media Sentiment Analysis